import type { NextPage } from 'next'
import { ref, onValue, set, push } from "firebase/database";
import { database } from '@/lib/config/firebase';
import { useState, useEffect } from 'react';
import { useList } from "react-firebase-hooks/database";

// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [snapshots, loading, error] = useList(ref(database, 'users'));
  const [users, setUsers] = useState("");
  const [data, setData] = useState({
    name: "",
    age: 0
  })

  useEffect(()=> {
    if (!loading && !error) {
      console.log(JSON.stringify(snapshots));
      //gets the users and puts it into a string
      setUsers(JSON.stringify(snapshots));
    }
  },[snapshots])

  const handleChange = (e: any) => {
    setData(prev=>({...prev,[e.target.name]: e.target.value}));
  }

  const handleSubmit = async (e: any) => {
    e.preventDefault();
    const usersRef = ref(database, 'users');
    const document = await push(usersRef);
    set(document, {
      name: data.name,
      age: data.age
    });
  }

  return (
    <div>
      <div className="text-white">{users}</div>
      <form onSubmit={handleSubmit} className="flex flex-col gap-5 mt-5 w-2/5 m-auto">
        <input type="text" name="name" value={data.name} onChange={handleChange}/>
        <input type='number' name="age" value={data.age} onChange={handleChange}/>
        <button type="submit" className="w-full p-3 bg-red-200">submit</button>
      </form>
    </div>
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by editing{' '}
    //       <code className={styles.code}>pages/index.tsx</code>
    //     </p>

    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>

    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>

    //       <a
    //         href="https://github.com/vercel/next.js/tree/canary/examples"
    //         className={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{' '}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
  )
}

export default Home
